### ISSUE TITLE
启动项目的时候，报错了 Cannot find module './manifest.json'

### ISSUE THREAD

**Issue by sai111** [cd-dongzi/vue-project#4]
Error: Cannot find module './manifest.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\shroom\vue-project\vue-toutiao\build\webpack.base.conf.js:87:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! toutiao@1.0.0 dev: `webpack-dev-server --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the toutiao@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\******\AppData\Roaming\npm-cache\_logs\2018-05-11T05_25_25_546Z-debug.log

**Comment by bewhatyouare** [comment]
先执行webpack --config ./build/webpack.dll.conf.js生成manifest.json

**Comment by AllenChenCD** [comment]
还是不行，启动报错

**Comment by liuyfCN** [comment]
cnpm run dll

**Comment by lcsone** [comment]
> VUE管理系统@ 3.1.1 DEV D:\ITDRAM\Web2\No.\0725Tay\VUE管理系统主控
> WebPultDever服务器----------------------------------------------------------------------------------------------------------------------------------------
“WebPACK DEV服务器”
最后一步。
NPM错误！代码周期
NPM错误！埃尔诺1
NPM错误！VUE管理系统@ 3.1.1 DEV：'WebPultDever服务器-在线-进度-CONFIG/WebPACK.DEV.CONF.JS
NPM错误！退出状态1
NPM错误！
NPM错误！在VUE管理系统@ 3.1.1 DEV脚本中失败。
NPM错误！这可能不是NPM的问题。上面可能还有额外的日志记录输出。
NPM警告本地包。JSON存在，但NoDEN1模块丢失，您是否打算安装？
NPM错误！此运行的完整日志可以在：
NPM错误！C：\\用户\Adabd\AppDAT\\ROMAM\NPM Cache \xLog\\2018－0906T06Y1111YOX4Y-44Z调试日志

**Comment by lcsone** [comment]
这是什么错啊

**Comment by liuyfCN** [comment]
不知道安？你是王杰？主分支的代码？我们这边还没放主分支啊，只是有个echarts那个好像需要单独安装，最开始没放在package.json里面

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ok406lhq** [comment]
我知道怎么做了

**Comment by ok406lhq** [comment]
> 这是什么错啊

你只要执行以下这个命令就可以了 npm run dll

**Comment by niejun123** [comment]
cnpm run dll

**Comment by niejun123** [comment]
cnpm Run dll

**Comment by liukaibaby** [comment]
我也同样的错误 什么情况 怎么解决 用了 npm run dll  cnpm Run dll都没用
